### ISSUE TITLE
Question: how to run script at startup?

### ISSUE THREAD

**Issue by alexlovar** [RMPR/atbswp#44]
Hello,  try to run a simple script that open a web browser link at startup, the script runs good from terminal but not from crontab.

@reboot python3 /home/pi/Downloads/test.py >>/home/pi/log.text 2>&1

**the script runs at startup but i have the follow error log:**

Traceback (most recent call last):
  File "/tmp/atbswp-20210204", line 4, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/home/pi/.local/lib/python3.7/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'

**Comment by RMPR** [comment]
Hi, seems like the fix is to use ```crontab -e display = 0 ``` see #40
