### ISSUE TITLE
atbswp.py on Windows: wxLocale::GetInfo() mismatch between C/C++ and Windows locale

### ISSUE THREAD

**Issue by firepol** [RMPR/atbswp#71]
## Checklist

- [x] I use the latest release of atbswp
- [x] The issue is not existing yet

## Verbose log

```
PS C:\Tools\atbswp> python.exe .\atbswp\atbswp.py
Traceback (most recent call last):
  File "C:\Tools\atbswp\atbswp\atbswp.py", line 32, in OnInit
    self.main = gui.MainDialog(None, wx.ID_ANY, "atbswp")
  File "C:\Tools\atbswp\atbswp\gui.py", line 133, in __init__
    self.icon = wx.Icon(os.path.join(self.path, "img", "icon.png"))
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
OnInit returned false, exiting...
```

### Operating System
Windows 10

### Desktop Environment/Window Manager
Windows 10

### Python version
3.9.7

## Description

On Linux, atbswp works fine, on Windows if I try to run atbswp.py as per instructions I get a wxLocale mismatch problem. You may tell me that this is a wxLocale issue, but I hope anybody has seen this issue and may help. Thank you

**Comment by firepol** [comment]
After reporting the issue I checked my region settings. I had

- Country: Switzerland
- Regional format: English (Switzerland)

Apparently the English (Switzerland) region was not liked by wxLocale... Maybe this could be useful to anybody with a similar issue, just check your region and try to fix it. I may be tempted to report this to wxPython as well...
